eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://host.docker.internal:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: host.docker.internal
spring:
  application:
    name: user-service
  cloud:
    discovery:
      enabled: true
      spring:
  data:
    mongodb:
      database: user_db
      port: 27017
      host: host.docker.internal

server:
  port: 3005
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  circuitBreaker:
    enable: true
logging:
  file:
    name: D:/Maveric/user-service/logs/userlog.log